version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: udea2025-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udea2025
      MYSQL_USER: udea
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: udea2025-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/udea2025
      SPRING_DATASOURCE_USERNAME: udea
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: udea2025-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
